title: Materia Medica Digitalis
author: Martin Munive, Medico General; Analista y programador de software
copyright: "2026 Martin Munive"
logo: ""

execute:
  execute_notebooks: "off"

exclude_patterns:
  - README.md
  - docs/**
  - venv/**
  - .venv/**
  - _build/**
  - .github/**

html:
  favicon: ""
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  baseurl: "https://martin-munive.github.io/Algoritmos-en-Python/"

repository:
  url: "https://github.com/Martin-Munive/Algoritmos-en-Python"
  path_to_book: ""
  branch: "main"

launch_buttons:
  notebook_interface: "classic"

sphinx:
  config:
    html_static_path:
      - _static
    html_css_files:
      - custom.css
    html_theme_options:
      home_page_in_toc: true
      repository_url: "https://github.com/Martin-Munive/Algoritmos-en-Python"
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
