title: Materia Médica Digitalis
author: Martin Munive, Médico General; Analista y programador de software
copyright: "2026 Martin Munive"
logo: ""

execute:
  execute_notebooks: "off"

exclude_patterns:
  - README.md
  - docs/**
  - venv/**
  - .venv/**
  - _build/**
  - _sources/**
  - .github/**

html:
  favicon: ""
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false
  use_download_button: false
  baseurl: "https://martin-munive.github.io/Materia_Medica_Digitalis/"

repository:
  url: "https://github.com/Martin-Munive/Materia_Medica_Digitalis"
  path_to_book: ""
  branch: "main"

launch_buttons:
  notebook_interface: "classic"

sphinx:
  config:
    html_copy_source: false
    html_show_sourcelink: false
    html_static_path:
      - _static
    html_css_files:
      - custom.css
    html_theme_options:
      home_page_in_toc: true
      repository_url: "https://github.com/Martin-Munive/Materia_Medica_Digitalis"
      use_repository_button: false
      use_issues_button: false
      use_edit_page_button: false
      use_download_button: false
